# -*- coding: utf-8 -*-
"""Final_Project_Data_Gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQSxeSYOTVQwpZbjZ4jj-StVNBi2HiUx
"""

!pip install --upgrade --force-reinstall sympy

from os import write
import random
import csv
from sympy import symbols, Eq, expand, simplify

x = symbols("x")

#TODO: Figure out tokenisation for the next token prediction alg


def clean_string(expr):
    '''
    Sympi returns powers as ** and multiplication as * so this puts
    this Sympi equations in more readable format
    '''
    return str(expr).replace("**", "^")


def format_factor(r):
    '''
    Format factors of an equation to be more readable
    in the form (x-6)
    '''
    if r > 0:
        return f"(x - {r})"
    elif r < 0:
        return f"(x + {abs(r)})"
    else:
        return "(x)"


def generate_linear_equation():
    '''
    Generatre a random linear equation in the format ax + b = c
    and returns for series of strings of solutions as input text and targets
    '''
    solution = random.randint(-10, 10)
    a = random.randint(1, 9)
    b = random.randint(-10, 10)
    c = a * solution + b

    eq = Eq(a * x + b, c)

    step1 = Eq(a * x, c - b)
    step2 = Eq(x, solution)

    return [
        {
            "type": "linear",
            "input_text": clean_string(eq.lhs) + " = " + clean_string(eq.rhs) + " ->",
            "target_text": clean_string(step1.lhs) + " = " + clean_string(step1.rhs)
        },
        {
            "type": "linear",
            "input_text": clean_string(step1.lhs) + " = " + clean_string(step1.rhs) + " ->",
            "target_text": clean_string(step2.lhs) + " = " + clean_string(step2.rhs)
        }
    ]


def generate_factorable_quadratic():
    '''
    Generate a random quadratic equation in the form (x-r1)(x-r2) = 0
    but then expands them so that they take the form ax^2 + bx + c = 0
    and returns string inputs and targets
    '''
    r1 = random.randint(-9, 9)
    r2 = random.randint(-9, 9)

    if r1 == 0 and r2 == 0:
        r2 = random.randint(1, 9)

    factored_expr = (x - r1) * (x - r2)
    expanded_expr = simplify(expand(factored_expr))

    expanded_text = clean_string(expanded_expr) + " = 0"
    factored_text = f"{format_factor(r1)} * {format_factor(r2)} = 0"
    solution_text = f"x = {r1} or x = {r2}"

    return [
        {
            "type": "quadratic",
            "input_text": expanded_text + " ->",
            "target_text": factored_text
        },
        {
            "type": "quadratic",
            "input_text": factored_text + " ->",
            "target_text": solution_text
        }
    ]


def generate_example():
    '''
    Helper function to generate an example either linear or quadratic
    '''

    kind = random.choice(["linear", "quadratic"])

    if kind == "linear":
        return generate_linear_equation()
    else:
        return generate_factorable_quadratic()

def generate_dataset(n_examples=1000):
    '''
    Generate a dataset of n_examples examples
    '''
    rows = []

    for _ in range(n_examples):
        example_rows = generate_example()
        rows.extend(example_rows)

    return rows

def save_dataset_csv(filename, examples):
    '''
    Save the dataset to a csv file
    '''
    with open(filename, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["type", "input_text", "target_text"])
        writer.writeheader()

        for ex in examples:
            writer.writerow(ex)

if __name__ == "__main__":
    examples = generate_dataset(30000)

    for ex in examples[:10]:
        print(ex["type"])
        print("INPUT :", ex["input_text"])
        print("TARGET:", ex["target_text"])
        print()

    save_dataset_csv("algebra_dataset.csv", examples)
    print("Saved dataset to algebra_dataset.csv")