# -*- coding: utf-8 -*-
"""Tokens and Embeding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1f9jOYomprLfyn_V-kY30-MdOJ3duTl
"""

from os import write
import random
import csv
from sympy import symbols, Eq, expand, simplify

import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

!pip install torchinfo
from torchinfo import summary

csv_path = "algebra_dataset (1).csv"

df = pd.read_csv(csv_path)
print(df.head())
print(df.shape)

def algebra_splitter(text):
    text = str(text).strip()
    tokens = []
    i = 0

    while i < len(text):
        ch = text[i]

        # handle arrow "->"
        if ch == '-' and i + 1 < len(text) and text[i + 1] == '>':
            tokens.append("->")
            i += 2
            continue

        # skip spaces
        if ch.isspace():
            i += 1
            continue

        # numbers (multi-digit)
        if ch.isdigit():
            num = ch
            i += 1
            while i < len(text) and text[i].isdigit():
                num += text[i]
                i += 1
            tokens.append(num)
            continue

        # variables (like x)
        if ch.isalpha():
            tokens.append(ch)
            i += 1
            continue

        # operators / parentheses
        if ch in "+-*/^=()":
            tokens.append(ch)
            i += 1
            continue

        # fallback (rare cases)
        tokens.append(ch)
        i += 1

    # add in explicit multiplication symbols
    new_tokens = []
    for j in range(len(tokens)):
        new_tokens.append(tokens[j])

        if j < len(tokens) - 1:
            a = tokens[j]
            b = tokens[j + 1]

            # cases where we want mult
            # x(, 2(, x x, 2 x, )x, )2
            if (
                (a.isdigit() and b.isalpha()) or
                (a.isalpha() and b.isalpha()) or
                (a in [")"] and (b.isalpha() or b.isdigit())) or
                ((a.isalpha() or a.isdigit()) and b in ["("])
            ):
                new_tokens.append("*")

    return new_tokens

def build_vocab(token_lists):
    # extra characters
    vocab = ["<PAD>", "<SOS>", "<EOS>", "<SEP>", "<UNK>"]

    for tokens in token_lists:
        for token in tokens:
            if token not in vocab:
                vocab.append(token)

    token_to_id = {token: i for i, token in enumerate(vocab)}
    id_to_token = {i: token for token, i in token_to_id.items()}

    return vocab, token_to_id, id_to_token

def encode(tokens, token_to_id):
    encoded = []

    for token in tokens:
        if token in token_to_id:
            encoded.append(token_to_id[token])
        else:
            encoded.append(token_to_id["<UNK>"])

    return encoded

def decode(ids, id_to_token):
    tokens = []

    for idx in ids:
        token = id_to_token[idx]

        if token == "<EOS>":
            break

        if token in ["<PAD>", "<SOS>"]:
            continue

        tokens.append(token)

    return tokens

example = "x(x - 9) = 0 ->"

split = algebra_splitter(example)
vocab, token_to_id, id_to_token = build_vocab([split])
tokens = encode(split, token_to_id)
decoded = decode(tokens, id_to_token)

token_df = pd.DataFrame({
    "Text": split,
    "Token": tokens
})

token_df.head(10)

class TargetOnlyNextTokenDataset(Dataset):
    def __init__(self, full_token_lists, token_to_id, context_length):
        self.data = []
        self.token_to_id = token_to_id
        self.context_length = context_length

        for tokens in full_token_lists:
            encoded = encode(tokens, token_to_id)

            sep_index = tokens.index("<SEP>")

            for i in range(context_length, len(encoded)):
                # only train on target side
                if i <= sep_index:
                    continue

                context = encoded[i - context_length:i]
                target = encoded[i]

                self.data.append((context, target))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        context, target = self.data[idx]
        return torch.tensor(context, dtype=torch.long), torch.tensor(target, dtype=torch.long)

csv_path = "algebra_dataset (1).csv"   # change if needed
df = pd.read_csv(csv_path)
full_token_lists = []

for inp, tgt in zip(df["input_text"], df["target_text"]):
    input_tokens = algebra_splitter(inp)
    target_tokens = algebra_splitter(tgt)

    full_tokens = ["<SOS>"] + input_tokens + ["<SEP>"] + target_tokens + ["<EOS>"]
    full_token_lists.append(full_tokens)

# build vocab
vocab, token_to_id, id_to_token = build_vocab(full_token_lists)

print("Number of equations:", len(full_token_lists))
print("Vocabulary size:", len(vocab))
print("First split example:", full_token_lists[0])

class SeuussModel(nn.Module):
    def __init__(self, vocab_size, context_length, embedding_dim, hidden_dim):
        super().__init__()
        self.context_length = context_length
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.net = nn.Sequential(
            nn.Linear(context_length * embedding_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, vocab_size)
        )

    def forward(self, x):
        embedded = self.embedding(x)
        flattened = embedded.view(embedded.shape[0], -1)
        return self.net(flattened)

context_length = 8

vocab, token_to_id, id_to_token = build_vocab(full_token_lists)

dataset = TargetOnlyNextTokenDataset(
    full_token_lists,
    token_to_id,
    context_length=context_length
)

loader = DataLoader(dataset, batch_size=64, shuffle=True)

print("Training examples:", len(dataset))
print("Vocab size:", len(vocab))

model = SeuussModel(
    vocab_size=len(vocab),
    context_length=context_length,
    embedding_dim=64,
    hidden_dim=256
).to(device)

loss_fn = nn.CrossEntropyLoss()
opt = torch.optim.Adam(model.parameters(), lr=1e-3)

loss_history = []

for epoch in range(30):
    model.train()
    total_loss = 0

    for X_batch, y_batch in loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        opt.zero_grad()
        preds = model(X_batch)
        loss = loss_fn(preds, y_batch)
        loss.backward()
        opt.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(loader)
    loss_history.append(avg_loss)
    print(f"Epoch {epoch+1}: loss = {avg_loss:.4f}")

def generate_solution(model, input_text, token_to_id, id_to_token,
                      max_new_tokens=30, temperature=2, greedy=True):
    tokens =  algebra_splitter(input_text)

    for step in range(max_new_tokens):
        context_tokens = tokens[-model.context_length:]

        while len(context_tokens) < model.context_length:
            context_tokens = ["<PAD>"] + context_tokens

        context_ids = encode(context_tokens, token_to_id)
        x = torch.tensor([context_ids], dtype=torch.long).to(device)

        with torch.no_grad():
            preds = model(x)[0]

            if step < 3:
              preds[token_to_id["<EOS>"]] = -1e9

            if greedy:
                next_id = torch.argmax(preds).item()
            else:
                preds = preds / temperature
                probs = torch.softmax(preds, dim=-1)
                next_id = torch.multinomial(probs, 1).item()

        next_token = id_to_token[next_id]

        if next_token == "<EOS>":
            break

        tokens.append(next_token)

    return tokens

def tokens_to_string(tokens):
    filtered = [t for t in tokens if t not in {"<PAD>", "<SOS>", "<EOS>"}]
    return "".join(filtered)

generated = generate_solution(
    model,
    "x^2 + 2x +1 = 0 ->",
    token_to_id,
    id_to_token,
    greedy=True
)

print(tokens_to_string(generated))