# -*- coding: utf-8 -*-
"""alg tokenizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R7YGJXUD5aYjKI-oHCBNJr5ACz3fc656
"""

class AlgebraTokenizer:
    def __init__(self):
        self.special_tokens = ["<PAD>", "<SOS>", "<EOS>", "<SEP>", "<UNK>"]
        self.vocab = []
        self.token_to_id = {}
        self.id_to_token = {}

    def build_vocab(self, token_lists):
        self.vocab = self.special_tokens.copy()

        for tokens in token_lists:
            for token in tokens:
                if token not in self.vocab:
                    self.vocab.append(token)

        self.token_to_id = {
            token: i for i, token in enumerate(self.vocab)
        }

        self.id_to_token = {
            i: token for token, i in self.token_to_id.items()
        }

        return self.vocab, self.token_to_id, self.id_to_token

    def encode(self, tokens):
        return [
            self.token_to_id.get(token, self.token_to_id["<UNK>"])
            for token in tokens
        ]

    def decode(self, ids):
        return [
            self.id_to_token.get(i, "<UNK>")
            for i in ids
        ]