# -*- coding: utf-8 -*-
"""data_set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BOiXoM8Qh-Qnvql3pSwwEPRYNJKszhop
"""

import torch
from torch.utils.data import Dataset

class TargetOnlyNextTokenDataset(Dataset):
    def __init__(self, full_token_lists, token_to_id, context_length):
        self.data = []
        self.token_to_id = token_to_id
        self.context_length = context_length
        self.pad_id = token_to_id["<PAD>"]

        for tokens in full_token_lists:
            encoded = encode(tokens, token_to_id)

            sep_index = tokens.index("<SEP>")

            for i in range(sep_index + 1, len(encoded)):
                # train only on target-side tokens
                start = max(0, i - context_length)

                context = encoded[start:i]

                # left pad to fixed context length
                if len(context) < context_length:
                    context = [self.pad_id] * (context_length - len(context)) + context

                target = encoded[i]

                self.data.append((context, target))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        context, target = self.data[idx]
        return torch.tensor(context, dtype=torch.long), torch.tensor(target, dtype=torch.long)