# -*- coding: utf-8 -*-
"""math_model2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ms21fW6iu7ZCy9lQ7iBy0moyyKEuanbJ
"""

import torch
import torch.nn as nn

# full transformer block model
class MathModel2(nn.Module):
  #https://www.geeksforgeeks.org/deep-learning/transformer-using-pytorch/
  #https://docs.pytorch.org/docs/2.11/generated/torch.nn.TransformerEncoderLayer.html?utm_source=chatgpt.com

    def __init__(
        self,
        vocab_size,
        context_length,
        embedding_dim=64,
        hidden_dim=256,
        num_heads=4,
        num_layers=4,
        pad_id=0,
        dropout=0.1
    ):
        super().__init__()

        self.context_length = context_length
        self.pad_id = pad_id

        # token embeddings
        self.token_embedding = nn.Embedding(vocab_size, embedding_dim)

        # positional embeddings
        self.position_embedding = nn.Embedding(context_length, embedding_dim)

        # transformer block
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embedding_dim,
            nhead=num_heads,
            dim_feedforward=hidden_dim,
            dropout=dropout,
            batch_first=True,
            activation="relu"
        )

        # stack multiple transformer blocks
        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers
        )

        self.norm = nn.LayerNorm(embedding_dim)

        # predict next token from final context position
        self.output = nn.Linear(embedding_dim, vocab_size)

    def forward(self, x):

        batch_size, seq_len = x.shape

        positions = torch.arange(seq_len, device=x.device)
        positions = positions.unsqueeze(0).expand(batch_size, seq_len)

        token_emb = self.token_embedding(x)
        pos_emb = self.position_embedding(positions)

        out = token_emb + pos_emb

        # mask padding tokens so attention does not focus on <PAD>
        padding_mask = x == self.pad_id

        out = self.transformer(
            out,
            src_key_padding_mask=padding_mask
        )

        out = self.norm(out)

        # use the last token in the context to predict the next token
        last_token = out[:, -1, :]

        logits = self.output(last_token)

        return logits