# -*- coding: utf-8 -*-
"""math_model1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4huj7cV8rtUz9PGOC7KVFU_6nT-KIjq
"""

import torch
import torch.nn as nn

class MathModel1(nn.Module):
    def __init__(self, vocab_size, context_length, embedding_dim, hidden_dim):
        super().__init__()

        self.context_length = context_length
        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        self.attention = nn.MultiheadAttention(
            embed_dim=embedding_dim,
            num_heads=4,
            batch_first=True # I could not figure out the error not having this setting was causing and used chatGPT for assistance.
        )

        self.norm1 = nn.LayerNorm(embedding_dim)

        self.net = nn.Sequential(
            nn.Linear(context_length * embedding_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, vocab_size)
        )

    def forward(self, x):
        embedded = self.embedding(x)

        attn_out, _ = self.attention(
            embedded,
            embedded,
            embedded
        )

        out = self.norm1(embedded + attn_out)

        flattened = out.reshape(out.shape[0], -1)

        return self.net(flattened)