# -*- coding: utf-8 -*-
"""seuss_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUzebOGwhXDDahjYPBHLQZaap0o8bbBa
"""

import torch
import torch.nn as nn

# Adapted from lecture notes
class SeussModel(nn.Module):
    def __init__(self, vocab_size, context_length, embedding_dim, hidden_dim):
        super().__init__()
        self.context_length = context_length
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.pipeline = nn.Sequential(
            nn.Linear(context_length * embedding_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, vocab_size)
        )

    def forward(self, x):
        embedded = self.embedding(x)
        flattened = embedded.view(embedded.shape[0], -1)
        return self.pipeline(flattened)
